[versions]
agp = "8.5.2"
basicMultiplatformLib = "0.1.0"
basicMultiplatformUiLib = "0.1.0R1"
kotlin = "2.1.10"
android-minSdk = "24"
android-compileSdk = "34"
kotlinxSerializationJson = "1.8.0"

[libraries]
basic-multiplatform-lib = { module = "io.github.octestx:basic-multiplatform-lib", version.ref = "basicMultiplatformLib" }
basic-multiplatform-ui-lib = { module = "io.github.octestx:basic-multiplatform-ui-lib", version.ref = "basicMultiplatformUiLib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }